AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - vendor/**/*
    - tmp/*
    - tmp/**/*
    - Brewfile

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 180
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Naming/VariableNumber:
  Enabled: false


